---
# Grafana default variables
grafana_version: "{{ lookup('env', 'GRAFANA_VERSION') | default('latest', true) }}"
grafana_http_port: "{{ lookup('env', 'GRAFANA_PORT') | default('3000', true) | int }}"
grafana_domain: "{{ lookup('env', 'GRAFANA_DOMAIN') | default('localhost', true) }}"
grafana_root_url: "{{ lookup('env', 'GRAFANA_ROOT_URL') | default('http://localhost:3000', true) }}"

# Grafana admin credentials
grafana_admin_user: "{{ lookup('env', 'GRAFANA_ADMIN_USER') | default('admin', true) }}"
grafana_admin_password: "{{ lookup('env', 'GRAFANA_ADMIN_PASSWORD') | default('admin', true) }}"

# Grafana security
grafana_secret_key: "{{ lookup('env', 'GRAFANA_SECRET_KEY') | default('SW2YcwTIb9zpOOhoPsMm', true) }}"
grafana_disable_gravatar: "{{ lookup('env', 'GRAFANA_DISABLE_GRAVATAR') | default('false', true) | bool }}"
grafana_allow_sign_up: "{{ lookup('env', 'GRAFANA_ALLOW_SIGN_UP') | default('false', true) | bool }}"

# Prometheus datasource
prometheus_datasource_url: "{{ lookup('env', 'PROMETHEUS_URL') | default('http://localhost:9090', true) }}"
prometheus_datasource_access: "{{ lookup('env', 'PROMETHEUS_ACCESS') | default('proxy', true) }}"
